site_name: The Julia Devito Inversion framework (JUDI.jl)
nav:
    - Home: index.md
    - Data structures: data_structures.md
    - Abstract vectors: abstract_vectors.md
    - Linear operators: linear_operators.md
    - IO: io.md
    - Applications: applications.md
    - About: about.md
theme: readthedocs
