site_name: The Julia Devito Inversion framework (JUDI.jl)
nav:
    - Home: index.md
    - Tutorials: tutorials.md
    - Data structures: data_structures.md
    - Abstract vectors: abstract_vectors.md
    - Linear operators: linear_operators.md
    - Input/Output: io.md
    - Helper functions: helper.md
    - Preconditioners: preconditioners.md
    - About: about.md
theme: readthedocs
