site_name: JUDI
site_description: The Julia Devito Inversion framework
site_url: https://slimgroup.github.io/JUDI.jl/
repo_url: https://github.com/slimgroup/JUDI.jl/

nav:
    - Home: index.md
    - Tutorials: tutorials.md
    - Data structures: data_structures.md
    - Abstract vectors: abstract_vectors.md
    - Linear operators: linear_operators.md
    - Input/Output: io.md
    - Helper functions: helper.md
    - Preconditioners: preconditioners.md
    - Python API: pysource.md
    - About: about.md

theme: readthedocs

copyright: Copyright 2020, SLIM @ Georgia Institute of Technology

plugins:
    - search